// Generated by CoffeeScript 1.6.3
(function() {
  var chdir, exec, initial, path;

  exec = require('child_process').exec;

  path = require('path');

  chdir = path.join(__dirname, '/..');

  initial = function() {
    var child;
    child = exec("" + chdir + "/scripts/initial.sh " + process.argv[2], function(err, stdout, stderr) {
      return console.log('finish');
    });
    return child.stdout.on('data', function(data) {
      return console.log(data);
    });
  };

  module.exports = initial;

}).call(this);
