// Generated by CoffeeScript 1.6.3
(function() {
  var Initial, initial;

  Initial = (function() {
    function Initial() {}

    return Initial;

  })();

  initial = new Initial;

  initial.Initial = Initial;

  module.exports = initial;

}).call(this);
